checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
builds:
  - id: ops_cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    binary: ops_cli_{{ .Os }}_{{ .Arch }}
    ldflags:
      - -s -w -X github.com/181192/ops-cli/pkg/util/version.Version={{.Version}} -X github.com/181192/ops-cli/pkg/util/version.GitCommit={{.Commit}}
archives:
  - format: binary

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - ops_cli
    image_templates:
      - "ghcr.io/181192/ops-cli:latest"
      - "ghcr.io/181192/ops-cli:{{ .Version }}"
    use_buildx: true
    skip_push: true
    build_flag_templates:
      - --platform=linux/amd64
      - --pull
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/181192/ops-cli
      - --label=org.opencontainers.image.source=https://github.com/181192/ops-cli
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - goos: linux
    goarch: arm64
    ids:
      - ops_cli
    image_templates:
      - "ghcr.io/181192/ops-cli:latest"
      - "ghcr.io/181192/ops-cli:{{ .Version }}"
    use_buildx: true
    skip_push: true
    build_flag_templates:
      - --platform=linux/arm64
      - --pull
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/181192/ops-cli
      - --label=org.opencontainers.image.source=https://github.com/181192/ops-cli
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: ghcr.io/181192/ops-cli:{{ .Version }}
  image_templates:
  - ghcr.io/181192/ops-cli:{{ .Version }}-amd64
  - ghcr.io/181192/ops-cli:{{ .Version }}-arm64
